/**
 * App-wide localization strings
 * Placeholder for future i18n implementation
 */

export const strings = {
  // Auth screens
  auth: {
    login: 'Log In',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account? Sign up",
    haveAccount: "Already have an account? Log in",
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    passwordMatch: 'Passwords must match',
    invalidEmail: 'Please enter a valid email',
    passwordLength: 'Password must be at least 6 characters',
  },
  
  // Onboarding
  onboarding: {
    welcome: 'Welcome to Respiratory Health',
    description: 'Monitor your respiratory health with advanced audio analysis',
    slide1Title: 'Record Your Cough',
    slide1Description: 'Simply record a cough sample with your phone',
    slide2Title: 'AI Analysis',
    slide2Description: 'Our AI analyzes your cough patterns',
    slide3Title: 'Track Progress',
    slide3Description: 'Monitor your respiratory health over time',
    getStarted: 'Get Started',
    skip: 'Skip',
    next: 'Next',
  },
  
  // Home screen
  home: {
    welcome: 'Welcome',
    guest: 'Guest',
    recordCTA: 'Record Sample',
    recentRecordings: 'Recent Recordings',
    viewAll: 'View All',
    noRecordings: 'No recordings yet',
    analyze: 'Analyze',
  },
  
  // Record screen
  record: {
    title: 'Record Sample',
    instructions: 'Press the microphone button to record a respiratory sample. Try to breathe normally for best results.',
    recording: 'Recording...',
    permission: 'Microphone access is required',
    retry: 'Retry',
    analyze: 'Analyze',
    seconds: 'seconds',
    save: 'Save Recording',
    cancel: 'Cancel',
    play: 'Play',
    pause: 'Pause',
    stop: 'Stop',
    tooShort: 'Recording too short',
    holdLonger: 'Please record for at least 3 seconds',
    tipsTitle: 'Tips for Better Results',
    tip1: 'Find a quiet environment with minimal background noise',
    tip2: 'Hold your device about 6 inches from your mouth',
    tip3: 'Breathe normally for at least 15 seconds',
  },
  
  // Analyze screen
  analyze: {
    title: 'Analysis Results',
    loading: 'Loading recording...',
    processing: 'Processing your recording...',
    analyze: 'Analyze Recording',
    analysisError: 'Failed to analyze recording',
    errorLoading: 'Failed to load recording',
    recordingNotFound: 'Recording not found',
    noSpectrogramData: 'No spectrogram data available',
    recordingInfo: 'Recording Information',
    recordedOn: 'Recorded On',
    duration: 'Duration',
    fileSize: 'File Size',
    seconds: 'seconds',
    play: 'Play Recording',
    pause: 'Pause Recording',
    analysisResults: 'Analysis Results',
    spectrogram: 'Spectrogram Visualization',
    respiratoryRate: 'Respiratory Rate',
    breathsPerMinute: 'breaths/min',
    condition: 'Condition',
    confidence: 'Confidence',
    interpretation: 'Interpretation',
    recommendations: 'Recommendations',
    share: 'Share Results',
    shareTitle: 'Respiratory Analysis Results',
    shareMessage: 'Here are my respiratory analysis results:',
    recordingDate: 'Recording Date',
    respiratoryCondition: 'Respiratory Condition',
    irregularities: 'Irregularities',
    detected: 'Detected',
    deleteRecording: 'Delete Recording',
    deleteConfirm: 'Delete Recording?',
    deleteMessage: 'This will permanently delete this recording and its analysis. This action cannot be undone.',
    deleteError: 'Failed to delete recording',
    sendToServer: 'Send to Server',
    sendingToServer: 'Sending to server...',
  },
  
  // History screen
  history: {
    title: 'Recording History',
    noRecordings: 'No recordings yet',
    startRecording: 'Press the button below to start recording',
    recordNew: 'Record New',
    recording: 'Recording',
    analyzed: 'Analyzed',
    all: 'All Recordings',
    analyzedFilter: 'Analyzed',
    unanalyzedFilter: 'Unanalyzed',
    deleteConfirmTitle: 'Delete Recording',
    deleteConfirmMessage: 'Are you sure you want to delete this recording?',
    deleteError: 'Failed to delete recording',
    unknownDuration: 'Unknown duration',
    seconds: 'seconds',
    cancel: 'Cancel',
    delete: 'Delete',
    share: 'Share',
    duration: 'Duration',
    date: 'Date',
    time: 'Time',
  },
  
  // Profile screen
  profile: {
    title: 'Profile',
    editProfile: 'Edit Profile',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    language: 'Language',
    about: 'About',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  
  // Common
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    ok: 'OK',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    settings: 'Settings',
  },
  
  // Errors
  errors: {
    permissionDenied: 'Permission denied',
    networkError: 'Network error',
    storageError: 'Storage error',
    lowStorage: 'Low storage space',
    unknownError: 'Something went wrong',
    microphoneRequired: 'Microphone access is required to record audio',
    storageRequired: 'Storage access is required to save recordings',
  },
};
